---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-storage-account-keys
  namespace: flux-system
spec:
  interval: 10m
  path: flux/infrastructure/configs/storage/azure_storage_account_keys/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age