apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values:
    controller:
      ingressClass: nginx
      service:
        type: LoadBalancer
      extraArgs:
        enable-ssl-passthrough: "true"
      metrics:
        enabled: true
      nodeSelector:
        kubernetes.io/os: linux