apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: "1.8.0" # Update to the latest version
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    # Specify any custom values for your Longhorn installation here
    defaultSettings:
      backupTarget: ""
