apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./"
  prune: true
  decryption:
    provider: sops
  sourceRef:
    kind: GitRepository
    name: flux-repo
